# Write a Python program to concatenate two 2-dimensional arrays

In [10]:
#importing numpy 
import numpy as np
#making two 2d arrays array
my_array_one = np.array([[0,1,3],[5,7,9]])
my_array_two = np.array([[0,2,4],[6,8,10]])

In [11]:
#displaying arrays
my_array_one

array([[0, 1, 3],
       [5, 7, 9]])

In [12]:
my_array_two

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [16]:
#concatenating both 2d arrays
new_array= np.concatenate((my_array_one, my_array_two), 1)
#displaying concatenated array
new_array

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])