# program to remove specific elements in a numpy array

In [10]:
import numpy as np
#making a demo array
my_array =np.array([10,20,30,40,50,60,70,80,90,100]) 

In [11]:
#deleting the element from specified position
new_array=np.delete(my_array,0)
#displaying new array
new_array

array([ 20,  30,  40,  50,  60,  70,  80,  90, 100])

In [12]:
#deleting the element from specified position
new_array_2=np.delete(new_array,3)
#displaying new array
new_array_2

array([ 20,  30,  40,  60,  70,  80,  90, 100])

In [13]:
#deleting the element from specified position
new_array_3=np.delete(new_array_2,2)
#displaying new array
new_array_3

array([ 20,  30,  60,  70,  80,  90, 100])